# Site settings
title: LIFS Research Blog
description: "Legal Informatics and Forensic Science Institute @ Hallym University"
url: "https://lifshallym.github.io/ResearchNotes"
author:
  name: "LIFS@Hallym"
  email: "de1880@hallym.ac.kr"
  url: "https://cis.hallym.ac.kr"

# Build settings
baseurl: /ResearchNotes # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
